# Generated by Django 2.1.5 on 2019-01-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTPDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('portnumber', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OMDB_API_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('API_KEY', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TMDB_API_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('API_KEY', models.CharField(max_length=300)),
                ('BaseImageLink', models.CharField(max_length=300)),
                ('BaseMovieInternetLink', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
