# Generated by Django 2.1.5 on 2019-01-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OMDB_API_Details',
            new_name='OMDBAPIDetails',
        ),
        migrations.RenameModel(
            old_name='TMDB_API_Details',
            new_name='TMDBAPIDetails',
        ),
    ]
