# Generated by Django 2.1.5 on 2019-02-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190129_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMDBAPIDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoviePageLink', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='tmdbapidetails',
            old_name='BaseMovieInternetLink',
            new_name='MoviePageLink',
        ),
        migrations.AddField(
            model_name='omdbapidetails',
            name='MoviePageLink',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
