# Generated by Django 2.1.5 on 2019-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20190201_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbapidetails',
            name='MoviePageLink',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tmdbapidetails',
            name='MoviePageLink',
            field=models.CharField(max_length=300),
        ),
    ]
