# Generated by Django 2.1.5 on 2019-02-09 07:57

import Series.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForTv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('initial_path', models.CharField(max_length=250)),
                ('background_image', models.FileField(blank=True, max_length=700, upload_to=Series.models.upload_location)),
                ('frontpage_feature', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreateSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=50)),
                ('destination_location', models.CharField(max_length=7024)),
                ('numberOfReleased', models.PositiveIntegerField()),
                ('numberOfUploaded', models.PositiveIntegerField()),
                ('API_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CreateTVSeries',
            fields=[
                ('TV_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TV_title', models.CharField(max_length=7024)),
                ('year', models.PositiveIntegerField()),
                ('TV_timeline', models.CharField(max_length=50)),
                ('numberOfSeason', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=7024)),
                ('rating', models.DecimalField(decimal_places=1, default=None, max_digits=5)),
                ('writer', models.CharField(max_length=7024)),
                ('cast', models.CharField(max_length=7024)),
                ('plot', models.CharField(max_length=6600)),
                ('poster_path', models.FileField(max_length=700, upload_to=Series.models.upload_location)),
                ('destination_location', models.CharField(max_length=7024)),
                ('is_featured', models.BooleanField(default=False)),
                ('API_name', models.CharField(max_length=20)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Series.CategoryForTv')),
            ],
        ),
        migrations.CreateModel(
            name='UploadEpisode',
            fields=[
                ('episode_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('episode_serial', models.PositiveIntegerField()),
                ('episode_title', models.CharField(blank=True, max_length=500)),
                ('episode_air_date', models.CharField(blank=True, max_length=500)),
                ('plot', models.CharField(blank=True, max_length=7024)),
                ('filepath', models.CharField(blank=True, max_length=7024)),
                ('destination_location', models.CharField(blank=True, max_length=7024)),
                ('API_name', models.CharField(blank=True, max_length=50)),
                ('episode_api_ID', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(blank=True, default=False)),
                ('is_converted', models.BooleanField(blank=True, default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5)),
                ('is_uploaded', models.BooleanField(blank=True, default=False)),
                ('TV_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Series.CreateTVSeries')),
                ('season_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Series.CreateSeason')),
            ],
        ),
        migrations.AddField(
            model_name='createseason',
            name='TV_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Series.CreateTVSeries'),
        ),
        migrations.AlterUniqueTogether(
            name='createseason',
            unique_together={('TV_title', 'season_id')},
        ),
    ]
