# Generated by Django 2.1.5 on 2019-02-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createseason',
            name='TV_ID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='createseason',
            unique_together={('TV_ID', 'season_id')},
        ),
    ]
