# Generated by Django 2.1.5 on 2019-02-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0002_auto_20190209_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createseason',
            name='TV_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='Series.CreateTVSeries'),
        ),
    ]
