# Generated by Django 2.1.5 on 2019-01-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('initial_path', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UploadMovie',
            fields=[
                ('movie_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=250)),
                ('IMDB_rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('director', models.CharField(max_length=250)),
                ('writer', models.CharField(max_length=250)),
                ('cast', models.CharField(max_length=250)),
                ('plot', models.CharField(max_length=300)),
                ('poster_path', models.ImageField(upload_to='media/')),
                ('store_path', models.CharField(max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_converted', models.BooleanField(default=False)),
                ('API_name', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Category')),
            ],
        ),
    ]
