# Generated by Django 2.1.5 on 2019-01-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmovie',
            old_name='category',
            new_name='category_id',
        ),
    ]
