# Generated by Django 2.1.5 on 2019-01-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190115_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmovie',
            old_name='store_path',
            new_name='destination_location',
        ),
    ]
