# Generated by Django 2.1.5 on 2019-01-16 12:38

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190116_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmovie',
            name='poster_path',
            field=models.ImageField(upload_to=movies.models.upload_location),
        ),
    ]
