# Generated by Django 2.1.5 on 2019-01-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190118_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmovie',
            name='cast',
            field=models.CharField(max_length=7024),
        ),
        migrations.AlterField(
            model_name='uploadmovie',
            name='destination_location',
            field=models.FilePathField(max_length=7024),
        ),
        migrations.AlterField(
            model_name='uploadmovie',
            name='director',
            field=models.CharField(max_length=7024),
        ),
        migrations.AlterField(
            model_name='uploadmovie',
            name='genre',
            field=models.CharField(max_length=7024),
        ),
        migrations.AlterField(
            model_name='uploadmovie',
            name='movie_title',
            field=models.CharField(max_length=7024),
        ),
        migrations.AlterField(
            model_name='uploadmovie',
            name='writer',
            field=models.CharField(max_length=7024),
        ),
    ]
