# Generated by Django 2.1.5 on 2019-01-22 11:28

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190122_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmovie',
            name='poster_path',
            field=models.FileField(max_length=700, upload_to=movies.models.upload_location),
        ),
    ]
