# Generated by Django 2.1.5 on 2019-01-29 10:34

from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20190122_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFeatureHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_poster', models.FileField(max_length=700, upload_to=movies.models.upload_location)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.UploadMovie')),
            ],
        ),
    ]
